/**
 * Embedding input-text assembly.
 *
 * The 384-dim all-MiniLM-L6-v2 embedding itself is generated by
 * Enrichment-Service (see ai/enrichment-client.ts). This module keeps only the
 * shared helper for building the concatenated text we send to the embedder.
 */

const MAX_TEXT_LENGTH = 8192; // Characters

/**
 * Build text for embedding from content fields.
 *
 * Order: title → transcript|body → excerpt. Caps total length to
 * MAX_TEXT_LENGTH so we don't blow past the model's input window.
 */
export function buildEmbeddingText(
    title: string,
    excerpt?: string | null,
    bodyText?: string | null,
    transcript?: string | null,
): string {
    const parts: string[] = [title];

    // Prefer transcript for video/podcast, otherwise use body text.
    if (transcript) {
        parts.push(transcript.substring(0, 2000));
    } else if (bodyText) {
        parts.push(bodyText.substring(0, 2000));
    }

    if (excerpt && excerpt !== bodyText?.substring(0, excerpt.length)) {
        parts.push(excerpt);
    }

    const combined = parts.join(' ').trim();
    return combined.substring(0, MAX_TEXT_LENGTH);
}
